CREATE TABLE IF NOT EXISTS users (
    user_id SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(320) UNIQUE NOT NULL,
    signup_date DATE NOT NULL DEFAULT CURRENT_DATE,
    domain VARCHAR(255)
);
